# Fly.io Configuration for Vatevo API
# This file configures the API deployment on Fly.io

app = "app-ezgnqzzi"
primary_region = "lhr"  # London (EU)
secondary_region = "fra"  # Frankfurt (EU)

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/ready"

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/live"

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/db"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024

# Health checks
[checks]
  [checks.ready]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/ready"

  [checks.live]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/live"

  [checks.database]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/db"

# Graceful shutdown
[deploy]
  release_command = "alembic upgrade head"
  strategy = "rolling"

# Concurrency settings
[processes]
  web = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2"

# Metrics
[metrics]
  port = 9090
  path = "/metrics"
