name: vatevo-api
region: ams3
services:
  - name: api
    dockerfile_path: apps/api/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /status
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: APP_ENV
        value: production
      - key: APP_VERSION
        value: "0.1.0"
# Trigger deployment
