name: vatevo-api
region: ams3
services:
  - name: api
    github:
      repo: gabriellagziel/vatEvo
      branch: main
      deploy_on_push: true
    source_dir: apps/api
    run_command: uvicorn apps.api.app.main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /status
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: APP_ENV
        value: production
      - key: APP_VERSION
        value: "0.1.0"
