name: API → Fly.io (prod)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "apps/api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build metadata
        id: meta
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy \
            --config apps/api/fly.toml \
            --build-arg GIT_SHA=${{ steps.meta.outputs.sha_short }} \
            --build-arg BUILD_TIME=${{ steps.meta.outputs.build_time }} \
            --build-arg APP_VERSION=0.1.0 \
            --build-arg APP_ENV=production \
            --remote-only

      - name: Verify /status
        run: curl -fsS https://app-ezgnqzzi.fly.dev/status | jq .

name: API Deploy (Prod Direct)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "apps/api/**"
      - "Dockerfile"
      - ".github/workflows/api-deploy-prod.yml"

env:
  FLY_APP: app-ezgnqzzi

jobs:
  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set build metadata timestamp
        id: meta
        run: echo "time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to Fly.io
        run: flyctl auth login --access-token "$FLY_API_TOKEN"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy API (prod)
        working-directory: apps/api
        run: |
          flyctl deploy --config ../../infra/fly.toml --app $FLY_APP --remote-only \
            --build-arg VERSION=0.1.0 \
            --build-arg GIT_SHA=${{ github.sha }} \
            --build-arg BUILD_TIME=${{ steps.meta.outputs.time }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Optional rollback instructions (commented)
      # rollback_prod:
      #   name: Rollback Production (Manual)
      #   runs-on: ubuntu-latest
      #   needs: [deploy_prod]
      #   steps:
      #     - name: Setup Flyctl
      #       uses: superfly/flyctl-actions/setup-flyctl@master
      #     - name: Login to Fly.io
      #       run: flyctl auth login --access-token "$FLY_API_TOKEN"
      #       env:
      #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #     - name: List releases
      #       run: flyctl releases list --app $FLY_APP
      #     - name: Revert to previous
      #       run: flyctl releases revert -y --app $FLY_APP $(flyctl releases list --app $FLY_APP --json | jq -r '.[1].version')
